### ISSUE TITLE
Add support for v2 api

### ISSUE THREAD

**Issue by styfle** [chinanf-boy/packagephobia-cli#2]
Now you don't need to scrape the html anymore.

For example: https://packagephobia.now.sh/v2/api.json?p=express@4.13.2

**Comment by chinanf-boy** [comment]
Sorry, missing your ISSue 😅
I will see

**Comment by chinanf-boy** [comment]
@styfle Ok, v2.0.0

https://github.com/chinanf-boy/packagephobia-cli/releases/tag/v2.0.0

**Comment by styfle** [comment]
@chinanf-boy Nice!
